"use client";

import { useTamboThread } from "@tambo-ai/react";

type ProjectTitleProps = {
  fallbackName?: string;
};

export const ProjectTitle = (props: ProjectTitleProps) => {
  const { thread } = useTamboThread();

  // Show thread name (auto-generated by Tambo) > fallback > "New Project"
  return <>{thread?.name || props.fallbackName || "New Project"}</>;
};
