"use client";

import { useTamboThread } from "@tambo-ai/react";

export const ProjectTitle = () => {
  const { thread } = useTamboThread();

  // Show thread name (auto-generated by Tambo) or "Untitled Project" while generating
  return <>{thread?.name || "Untitled Project"}</>;
};
